Repository Feortegas/OnTrack, pull requests merged in 2022-03, with the labels that each got.

#12 added auth in server and client folders. Also added packages in the c…
  .gitignore
  client/src/utils/auth.js
  server/utils/auth.js
Labels: Backend

#13 Issue/1 database
  README.md
  server/.gitignore
  server/models/Issue.js
  server/models/Project.js
  server/models/Team.js
  server/models/User.js
  server/models/index.js
Labels: Backend

#24 Issue/4 GitHub api
  README.md
  server/api/github.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: Backend

#58 Issue/32 connect front backend
  client/src/api/github.js
  client/src/components/Dashboard/index.js
  client/src/components/Project/index.js
  client/src/components/ProjectModal/index.js
  client/src/components/Team/index.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/models/Contributor.js
  server/models/Issue.js
  server/models/Project.js
  server/models/User.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: Backend, Frontend

#59 Develop to main
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.js
  client/src/api/github.js
  client/src/components/Dashboard/index.js
  client/src/components/Landing/index.js
  client/src/components/Login/index.js
  client/src/components/Project/index.js
  client/src/components/ProjectModal/index.js
  client/src/components/Team/index.js
  client/src/utils/auth.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  package.json
  server/api/github.js
  server/models/Contributor.js
  server/models/Issue.js
  server/models/Project.js
  server/models/User.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/seeders/seeds.js
  server/server.js
  server/utils/auth.js
Labels: enhancement
